### PR TITLE
Fixed #6

### LINKED ISSUE #6: Incorrect OCaml implementation of SHA256?
When compiling with digestif.ocaml, the SHA256 hash result obtained via feeding and getting does not match the Nocrypto's one.

But when compiled with digestif.c, the hash matches.

When compiled with digestif.ocaml, it seems that the hashes mismatch as well if feeding size is different for each round.

I have not tried other hash algorithms.

Please let me know if you want me to provide full code to demonstrate the issue.

### PR DESCRIPTION
**Pull request by dinosaure**

### CODE REVIEW

File: src-ocaml/baijiu_md5.ml [hunk 1]
```diff
@@ -178,9 +178,12 @@ module Make (B : Baijiu_buffer.S)
       idx := 0;
     end;
 
+    Format.printf "len: %d, off: %d, idx: %d.\n%!"
+      !len !off !idx;
+
```
Comment (samoht) [inline src-ocaml/baijiu_md5.ml]: is this supposed to be there?

Comment (dinosaure) [inline src-ocaml/baijiu_md5.ml]: Ah, thanks, I believed delete all logs :( ...
